### ISSUE TITLE
Function Literal formatting seems off

### ISSUE THREAD

**Issue by ZakTaccardi** [pinterest/ktlint#2818] opened 2024-10-01 18:50 UTC
`function-literal` ([docs](https://pinterest.github.io/ktlint/1.3.1/rules/standard/#function-literal)) formatting seems off.

When calling into this function:
```kt
@file:Suppress("NO_EXPLICIT_VISIBILITY_IN_API_MODE_WARNING")

package com.capitalone.android.identity.challenge.internal.logic

fun <T1, T2, R> combine(
    result1: Result<T1>,
    result2: Result<T2>,
    transform: suspend (T1, T2) -> R
) {
    TODO()
}
```

## Expected Behavior
I would expect something like this:
```kt
fun usageExpected(result1: Result<Int>, result2: Result<String>) {
    combine(
        result1 = result1,
        result2 = result2
    ) { one: Int,
        two: String ->
        "$one$two"
    }
}
```

## Observed Behavior
But instead, we get this:
```kt
fun usageActual(result1: Result<Int>, result2: Result<String>) {
    combine(
        result1 = result1,
        result2 = result2
    ) {
            one: Int,
            two: String
        ->
        "$one$two"
    }
}
```

The parameters (`one: Int` and `two: String`) being indented an extra 4 spaces seems very off to me.

## Your Environment
* Version of ktlint used: `1.3.1`

**Comment by paul-dingemans** [comment] 2024-10-02 05:41
Duplicate of #2816

**Closed by paul-dingemans** 2024-10-02 05:41 UTC
