### ISSUE TITLE
Issue with fun interface in kotlin 1.4

### ISSUE THREAD

**Issue by Ezike** [pinterest/ktlint#781] opened 2020-06-11 13:04 UTC
@shashachu  I'm getting this error because I'm using the functional interfaces from kotlin1.4-M2
```
29:8 Expecting function name or receiver type
com.pinterest.ktlint.core.ParseException: 29:8 Expecting function name or receiver type
```

This is the code
```
   fun interface OptionClickListener {
        fun onOptionSelected(item: PhoneTransferOpModel)
    }
```

Any chance support for kotlin 1.4 will come soon..
I'm using the spotless plugin with ktlint

**Comment by Tapchicoma** [comment] 2020-06-11 13:11
Dup of #771

**Comment by JakeWharton** [comment] 2020-06-11 13:11
Dupe of #771

**Closed by Tapchicoma** 2020-06-11 13:11 UTC

**Comment by Ezike** [comment] 2020-06-11 13:14
alright thanks @JakeWharton @Tapchicoma  .. I'll just go back to good ol interfaces for now I guess. Any other suggestions?

**Comment by pravee1801** [comment] 2024-09-07 11:51
I have a similiar fun interface Notifier<T> {
        fun notify(model: T?, action: Action)
    } in my kotlin project and its completely fine, but I get mvn spotless error with this 
    `Execution default-cli of goal com.diffplug.spotless:spotless-maven-plugin:2.4.1:apply failed: Expecting function name or receiver type`
    Does anybody have any solution for this?

**Comment by paul-dingemans** [comment] 2024-09-09 13:11
What about updating yoyr spotless-maven-plugin? Current stable version is 2.43 (https://github.com/diffplug/spotless/releases/tag/maven%2F2.43.0). You are running almost 40 versions behind....
