### ISSUE TITLE
Multiline primary constructor trips up the indent rule

### ISSUE THREAD

**Issue by vatbub** [pinterest/ktlint#2251] opened 2023-09-07 12:51 UTC
## Expected Behavior
Consider the following code:

```kotlin
package de.uni_freiburg.inatech.streem.feature_analyzer.view.option_modules

class ClassWithMultilineConstructor
@Deprecated(
    "Constructor must only be called by JavaFX.",
    ReplaceWith("ClassWithMultilineConstructor.newInstance()"),
    DeprecationLevel.ERROR
)
constructor() {
    private val stringMember = "Hello there"

    fun someMethod() {
        println("Hello there")
    }

    companion object {
        fun newInstance(): ClassWithMultilineConstructor {
            println("Method in the companion object called")
            return ClassWithMultilineConstructor::class.java.getDeclaredConstructor().newInstance()
        }
    }
}
```

The annotation and constructor have to be wrapped this way or else the max line length would be reached.

## Observed Behavior
KtLint wants the entire class to be indented by one more tab, which not only looks ugly but also fights IntelliJ:

```
ClassWithMultilineConstructor.kt:4:1: Unexpected indentation (0) (should be 4) (standard:indent)
ClassWithMultilineConstructor.kt:5:1: Unexpected indentation (4) (should be 8) (standard:indent)
ClassWithMultilineConstructor.kt:6:1: Unexpected indentation (4) (should be 8) (standard:indent)
ClassWithMultilineConstructor.kt:7:1: Unexpected indentation (4) (should be 8) (standard:indent)
ClassWithMultilineConstructor.kt:8:1: Unexpected indentation (0) (should be 4) (standard:indent)
ClassWithMultilineConstructor.kt:9:1: Unexpected indentation (0) (should be 4) (standard:indent)
ClassWithMultilineConstructor.kt:10:1: Unexpected indentation (4) (should be 8) (standard:indent)
ClassWithMultilineConstructor.kt:12:1: Unexpected indentation (4) (should be 8) (standard:indent)
ClassWithMultilineConstructor.kt:13:1: Unexpected indentation (8) (should be 12) (standard:indent)
ClassWithMultilineConstructor.kt:14:1: Unexpected indentation (4) (should be 8) (standard:indent)
ClassWithMultilineConstructor.kt:16:1: Unexpected indentation (4) (should be 8) (standard:indent)
ClassWithMultilineConstructor.kt:17:1: Unexpected indentation (8) (should be 12) (standard:indent)
ClassWithMultilineConstructor.kt:18:1: Unexpected indentation (12) (should be 16) (standard:indent)
ClassWithMultilineConstructor.kt:19:1: Unexpected indentation (12) (should be 16) (standard:indent)
ClassWithMultilineConstructor.kt:20:1: Unexpected indentation (8) (should be 12) (standard:indent)
ClassWithMultilineConstructor.kt:21:1: Unexpected indentation (4) (should be 8) (standard:indent)
ClassWithMultilineConstructor.kt:22:1: Unexpected indentation (0) (should be 4) (standard:indent)
```

If I remove the `@Deprecated` annotation and the `constructor()` keyword (thus having the entire class signature on one line), the issue goes away.

## Steps to Reproduce
Run KtLint 1.0.0 on the previous code sample (0.50.0 did not have this issue). 

## Your Environment
* Version of ktlint used: 1.0.0
* Relevant parts of the `.editorconfig` settings:
```
indent_size = 4
indent_style = space
insert_final_newline = true
max_line_length = 120
tab_width = 4
ij_continuation_indent_size = 4
```

* Name and version (or code for custom task) of integration used: Maven 3.9.3 with the antrun-plugin
* Operating System and version: Windows 10

**Comment by vatbub** [comment] 2023-09-07 14:14
It seems like this is related to #2115 .

**Comment by paul-dingemans** [comment] 2023-09-07 16:14
Duplicate of #2138

**Closed** 2023-09-07 16:22 UTC
