### ISSUE TITLE
Unable to use negate pattern to ignore certain file locations

### ISSUE THREAD

**Issue by girish3** [pinterest/ktlint#1084] opened 2021-02-16 04:15 UTC
I used the same example as mentioned in the README.md

`ktlint "src/**/*.kt" "!src/**/*Test.kt"`

but I get the error as,
`zsh: event not found: src/`

Is there special handling for the `!` character in ktlint or in bash? Please help.

ktlint version: 0.40.0

**Comment by romtsn** [comment] 2021-02-16 11:49
Duplicate of #999

**Closed by romtsn** 2021-02-16 11:49 UTC

**Comment by chrihunstad** [comment] 2021-09-13 13:22
Both https://github.com/pinterest/ktlint/issues/999 and this issue is closed, but I also get this error following the example mentioned in the README.

Version: 0.42.1
