### ISSUE TITLE
Placing `// ktlint-disable` at top of file crashes ktlint

### ISSUE THREAD

**Issue by AndrewReitz** [pinterest/ktlint#1029] opened 2020-12-23 04:08 UTC
Step to Reproduce
Pick any kotlin file add at the very top add `// ktlint-disable`
Run ktlint lint

Following Stacktrace will be printed out

```
com.pinterest.ktlint.core.RuleExecutionException: kotlin.UninitializedPropertyAccessException: lateinit property importSorter has not been initialized
        at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:93)
        at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:23)
        at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:206)
        at com.pinterest.ktlint.core.KtLint$visitor$2$1.invoke(KtLint.kt:23)
        at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:224)
        at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:225)
        at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:204)
        at com.pinterest.ktlint.core.KtLint$visitor$2.invoke(KtLint.kt:23)
        at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:74)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction.lint(LintWorkerAction.kt:71)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction.lintKt(LintWorkerAction.kt:65)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction.access$lintKt(LintWorkerAction.kt:19)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction$execute$2$lintFunc$1.invoke(LintWorkerAction.kt:40)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction$execute$2$lintFunc$1.invoke(LintWorkerAction.kt:19)
        at org.jmailen.gradle.kotlinter.tasks.lint.LintWorkerAction.execute(LintWorkerAction.kt:47)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)
        at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property importSorter has not been initialized
        at com.pinterest.ktlint.ruleset.standard.ImportOrderingRule.visit(ImportOrderingRule.kt:95)
        at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:81)
        ... 46 more
```

**Comment by Tapchicoma** [comment] 2020-12-27 14:46
I could not reproduce it neither with build from `master` nor from `0.40.0` tag using following test file:
```kotlin
// ktlint-disable

fun test() {}
```

Have you tried to run ktlint CLI over failing file (maybe it is a bug in Gradle plugin)? Could you provide more information?

**Comment by AndrewReitz** [comment] 2020-12-27 18:13
I think it must be the package statement.

```
// ktlint-disable
package ktlint.test

import kotlin.math.sqrt

fun test() {
    
}
```

fails for me on 0.40.0 with 
> /Users/andrewreitz/test.kt:4:1: Internal Error (import-ordering). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, provide the source code that triggered an error) (cannot be auto-corrected)

**Comment by Tapchicoma** [comment] 2020-12-27 18:21
Yes, with `package` I could reproduce it :+1:

**Comment by Tapchicoma** [comment] 2020-12-27 18:30
Seems not a `package` here, but `import` is important.

**Comment by paul-dingemans** [comment] 2021-01-09 17:23
According to the documentation, the directive should be placed as EOL comment after the package statement. That also resulted in a problem, but has been fixed in this [PR](https://github.com/pinterest/ktlint/pull/1038).

**Comment by paul-dingemans** [comment] 2022-06-04 15:55
The statement `// ktlint-disable` at the top of the file is really ambiguous to disable all rules for the entire file.

Use below to suppress all rules in the entire file:
```
@file:Suppress("ktlint")
```
or provide a named list of rules to suppress in the entire file:
```
@file:Suppress("ktlint:no-foo-identifier-standard", "ktlint:custom:no-foo-identifier")
```

**Closed** 2022-06-07 16:38 UTC
Labels: bug
