### ISSUE TITLE
Show full path to files with errors

### ISSUE THREAD

**Issue by lwasyl** [pinterest/ktlint#560] opened 2019-08-15 17:18 UTC
Right now paths to files with errors are relative, which makes them non-clickable in IntelliJ/AndroidStudio:

![image](https://user-images.githubusercontent.com/3951580/63112565-cf8f9480-bf90-11e9-8dd8-8b31807ec735.png)

For comparison, Detekt shows full paths to files with violations, which makes them clickable in IDE build/terminal windows:

![image](https://user-images.githubusercontent.com/3951580/63112661-0f567c00-bf91-11e9-9df2-89901938fb07.png)

This is very convenient, especially since IDE will immediately navigate to proper line as well.

Is there an option right now to enable such behavior for ktlint? I'm using Kotlinter, but I believe it doesn't provide output itself. I'd also like to avoid writing custom reporter for that (is it even possible to change the stdout reporter?)

**Comment by Monchi** [comment] 2019-10-02 10:23
This seems to be fixed in latest master
![image](https://user-images.githubusercontent.com/16265411/66037199-0c681880-e54a-11e9-8b92-76bb22d62acb.png)

**Comment by Tapchicoma** [comment] 2019-10-03 19:59
Checked it and the problem is in Kotlinter plugin. Running ktlint via custom JavaExec task or ktlint-gradle plugin outputs full path to failed file.

Please open the issue in Kotlinter issue tracker.

**Closed by Tapchicoma** 2019-10-03 19:59 UTC
