### ISSUE TITLE
Provide windows batch file for running ktlint with java 16+

### ISSUE THREAD

**Issue by zackees** [pinterest/ktlint#1986] opened 2023-04-30 22:15 UTC
## Command run:

`java -jar tools/ktlint -F --log-level info`

Note that if I remove the `-F` argument it works fine.

Results in: `java.lang.ExceptionInInitializerError`
See below for stack trace

## Expected Behavior

I expected the tool to run to completion

## Observed Behavior
```
C:\Users\niteris\dev\androidmonitor-client>java -jar tools/ktlint -F --log-level info
15:11:10.237 [main] INFO com.pinterest.ktlint.cli.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.pinterest.ktlint.cli.internal.KtlintCommandLine.parallel(KtlintCommandLine.kt:692)
        at com.pinterest.ktlint.cli.internal.KtlintCommandLine.parallel$default(KtlintCommandLine.kt:645)
        at com.pinterest.ktlint.cli.internal.KtlintCommandLine.lintFiles(KtlintCommandLine.kt:422)
        at com.pinterest.ktlint.cli.internal.KtlintCommandLine.run(KtlintCommandLine.kt:323)
        at com.pinterest.ktlint.Main.main(Main.kt:35)
Caused by: java.lang.ExceptionInInitializerError
        at org.jetbrains.kotlin.com.intellij.util.exception.FrequentErrorLogger.report(FrequentErrorLogger.java:47)
        at org.jetbrains.kotlin.com.intellij.util.exception.FrequentErrorLogger.info(FrequentErrorLogger.java:43)
        at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.handleUnspecifiedTrace(DebugUtil.java:628)
        at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.currentInvalidationTrace(DebugUtil.java:620)
        at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.calcInvalidationTrace(DebugUtil.java:614)
        at org.jetbrains.kotlin.com.intellij.psi.impl.DebugUtil.onInvalidated(DebugUtil.java:585)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.TreeElement.onInvalidated(TreeElement.java:226)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.TreeElement.invalidate(TreeElement.java:328)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.TreeElement.rawRemove(TreeElement.java:312)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.TreeElement.rawReplaceWithList(TreeElement.java:319)
        at org.jetbrains.kotlin.com.intellij.psi.impl.source.tree.LeafElement.rawReplaceWithText(LeafElement.java:146)
        at com.pinterest.ktlint.ruleset.standard.rules.BlockCommentInitialStarAlignmentRule.beforeVisitChildNodes(BlockCommentInitialStarAlignmentRule.kt:58)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$1.invoke(RuleExecutionContext.kt:93)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$1.invoke(RuleExecutionContext.kt:92)
        at com.pinterest.ktlint.rule.engine.internal.SuppressHandler.handle-dhiVX_g(SuppressHandler.kt:28)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.executeRuleOnNodeRecursively(RuleExecutionContext.kt:92)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.access$executeRuleOnNodeRecursively(RuleExecutionContext.kt:29)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:100)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.SuppressHandler.handle-dhiVX_g(SuppressHandler.kt:28)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.executeRuleOnNodeRecursively(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.access$executeRuleOnNodeRecursively(RuleExecutionContext.kt:29)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:100)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.SuppressHandler.handle-dhiVX_g(SuppressHandler.kt:28)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.executeRuleOnNodeRecursively(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.access$executeRuleOnNodeRecursively(RuleExecutionContext.kt:29)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:100)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.SuppressHandler.handle-dhiVX_g(SuppressHandler.kt:28)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.executeRuleOnNodeRecursively(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.access$executeRuleOnNodeRecursively(RuleExecutionContext.kt:29)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:100)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.SuppressHandler.handle-dhiVX_g(SuppressHandler.kt:28)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.executeRuleOnNodeRecursively(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.access$executeRuleOnNodeRecursively(RuleExecutionContext.kt:29)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:100)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext$executeRuleOnNodeRecursively$2$1.invoke(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.SuppressHandler.handle-dhiVX_g(SuppressHandler.kt:28)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.executeRuleOnNodeRecursively(RuleExecutionContext.kt:99)
        at com.pinterest.ktlint.rule.engine.internal.RuleExecutionContext.executeRule(RuleExecutionContext.kt:61)
        at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine$format$3.invoke(KtLintRuleEngine.kt:136)
        at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine$format$3.invoke(KtLintRuleEngine.kt:135)
        at com.pinterest.ktlint.rule.engine.internal.VisitorProvider$visitor$3.invoke(VisitorProvider.kt:46)
        at com.pinterest.ktlint.rule.engine.internal.VisitorProvider$visitor$3.invoke(VisitorProvider.kt:44)
        at com.pinterest.ktlint.rule.engine.api.KtLintRuleEngine.format(KtLintRuleEngine.kt:135)
        at com.pinterest.ktlint.cli.internal.KtlintCommandLine.format(KtlintCommandLine.kt:479)
        at com.pinterest.ktlint.cli.internal.KtlintCommandLine.process(KtlintCommandLine.kt:465)
        at com.pinterest.ktlint.cli.internal.KtlintCommandLine.access$process(KtlintCommandLine.kt:64)
        at com.pinterest.ktlint.cli.internal.KtlintCommandLine$lintFiles$3.invoke$lambda$0(KtlintCommandLine.kt:416)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private transient java.lang.Object java.lang.Throwable.backtrace accessible: module java.base does not "opens java.lang" to unnamed module @1b0375b3
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.jetbrains.kotlin.com.intellij.util.ReflectionUtil.findFieldInHierarchy(ReflectionUtil.java:154)
        at org.jetbrains.kotlin.com.intellij.util.ReflectionUtil.getDeclaredField(ReflectionUtil.java:279)
        at org.jetbrains.kotlin.com.intellij.openapi.util.objectTree.ThrowableInterner.<clinit>(ThrowableInterner.java:88)
        ... 55 more
```

## Steps to Reproduce

Sorry, the code repo is private. But I can share it privately if you'd like. Just reach out and I'll arrange.

#### .editorconfig

```
[*.{kt,kts}]
ktlint_code_style = android
max_line_length = off
ktlint_standard_no-wildcard-imports = disabled
ktlint_code_style=android_studio
```

### KTLint Version
Version: 0.49 (but same problem is present on 0.48.2)

### Version of gradle

```
------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (Oracle Corporation 17.0.6+9-LTS-190)
OS:           Windows 10 10.0 amd64
```

### Operating System and version:

Windows 10. Also happens on Mac

**Comment by paul-dingemans** [comment] 2023-05-01 06:51
Most likely this problem is caused by running with java 17 without opening the required library that is needed for formatting. Please try adding jvmarg `--add-opens=java.base/java.lang=ALL-UNNAMED` or run with java 11.

**Comment by zackees** [comment] 2023-05-01 17:13
Thanks, that worked. And yes, I'm running in Java 17.

For those running into this problem here are the lint.bat and lint.sh files

**lint.bat**:
```
@echo off
java --add-opens=java.base/java.lang=ALL-UNNAMED -jar tools/ktlint -F --log-level info 
```

**lint.sh**:
```
#!/bin/bash
# java -jar tools/ktlint -F --log-level info
java --add-opens=java.base/java.lang=ALL-UNNAMED -jar tools/ktlint -F --log-level info
```

**Comment by zackees** [comment] 2023-05-01 21:27
Is closing this issue the best path? The issue still exists, there is just a workaround.

**Comment by paul-dingemans** [comment] 2023-05-05 12:58
I agree that the issue should not be closed. For Windows users it would be more convenient if the `lint.bat` would be exposed as an artifact in the release. I am not sure about the `lint.sh` though as `ktlint` is a self-executable file which already opens up the required java libs. @zackees, is there a reason that you think that `lint.sh` is of value to Windows users (e.g. can the `ktlint` executable be run via Git Bash?)

**Comment by zackees** [comment] 2023-05-07 21:48
Yes the `lint.sh` has been tested to run on git-bash in windows. However, this is just my little boilerplate script to run `ktlint` as I see fit.

**Comment by paul-dingemans** [comment] 2023-05-08 07:02
I had no doubts about `lint sh` running on Git bash. My question is whether the self executable fat jar, e.g. `ktlint` without extension, can be run on Git bash in same way as on Linux. For example `ktlint --version`. This would make the `lint.sh` redundant.

**Comment by zackees** [comment] 2023-05-17 19:19
Sure. Here is my updated `lint.bat`

```
@echo off
REM Note that --add-opens argument is needed for java 17
REM See https://github.com/pinterest/ktlint/issues/1986
java --add-opens=java.base/java.lang=ALL-UNNAMED -jar tools/ktlint %*
```

Here are the test results:

`lint.bat`

```
C:\Users\niteris\dev\androidmonitor-client>lint
12:16:56.963 [main] INFO com.pinterest.ktlint.cli.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
```

`lint.bat -F`:
```
12:15:51.757 [main] INFO com.pinterest.ktlint.cli.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
```

`lint.bat -F --log-level=debug`

```
C:\Users\niteris\dev\androidmonitor-client>lint.bat -F --log-level=debug   
12:17:28.495 [main] INFO com.pinterest.ktlint.cli.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
12:17:28.506 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered RuleSetProviderV3 with id 'standard' in ktlint JAR
12:17:28.668 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'baseline' in ktlint JAR
12:17:28.668 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'plain' in ktlint JAR
12:17:28.668 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'checkstyle' in ktlint JAR
12:17:28.669 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'json' in ktlint JAR
12:17:28.669 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'format' in ktlint JAR
12:17:28.669 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'html' in ktlint JAR
12:17:28.669 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'plain-summary' in ktlint JAR
12:17:28.669 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'sarif' in ktlint JAR
12:17:28.670 [main] DEBUG com.pinterest.ktlint.cli.internal.ReporterAggregator - Initializing "plain" reporter with {plain=true, color=false, color_name=DARK_GRAY, format=true}
12:17:28.678 [main] DEBUG com.pinterest.ktlint.cli.internal.FileUtils - Start walkFileTree for rootDir: 'C:\Users\niteris\dev\androidmonitor-client'
   include:
[      - sun.nio.fs.WindowsFileSystem$2@456d6c1e,       - sun.nio.fs.WindowsFileSystem$2@1e13529a,       - sun.nio.fs.WindowsFileSystem$2@1ec9bd38,       - sun.nio.fs.WindowsFileSystem$2@452e19ca]
   exclude:
[]
```
(truncated)

`lint.bat -F --log-level=debug --relative`:

```
12:18:23.083 [main] INFO com.pinterest.ktlint.cli.internal.KtlintCommandLine - Enable default patterns [**/*.kt, **/*.kts]
12:18:23.092 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered RuleSetProviderV3 with id 'standard' in ktlint JAR
12:18:23.246 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'baseline' in ktlint JAR
12:18:23.246 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'plain' in ktlint JAR
12:18:23.247 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'checkstyle' in ktlint JAR
12:18:23.247 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'json' in ktlint JAR
12:18:23.247 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'format' in ktlint JAR
12:18:23.247 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'html' in ktlint JAR
12:18:23.247 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'plain-summary' in ktlint JAR
12:18:23.247 [main] DEBUG com.pinterest.ktlint.cli.internal.KtlintServiceLoader - Discovered ReporterProviderV2 with id 'sarif' in ktlint JAR
12:18:23.248 [main] DEBUG com.pinterest.ktlint.cli.internal.ReporterAggregator - Initializing "plain" reporter with {plain=true, color=false, color_name=DARK_GRAY, format=true}
12:18:23.257 [main] DEBUG com.pinterest.ktlint.cli.internal.FileUtils - Start walkFileTree for rootDir: 'C:\Users\niteris\dev\androidmonitor-client'
   include:
[      - sun.nio.fs.WindowsFileSystem$2@456d6c1e,       - sun.nio.fs.WindowsFileSystem$2@1e13529a,       - sun.nio.fs.WindowsFileSystem$2@1ec9bd38,       - sun.nio.fs.WindowsFileSystem$2@452e19ca]
   exclude:
[]
12:18:23.431 [main] DEBUG com.pinterest.ktlint.cli.internal.FileUtils - Discovered 48 files to be processed in 173 ms
```
(truncated)

**Comment by paul-dingemans** [comment] 2023-05-17 19:38
Cool. Only thing that might need improvement is the path to the jar file. When downloading a ktlint release the bat and jar file will be in same directory. So maybe you can add a variable for the JAR_PATH and add a comment that this var needs to be changed if bat and jar file are not located in same dir.

**Comment by zackees** [comment] 2023-05-17 23:23
Again, thanks for you help with this. ktlint is invaluable and not having it when I upgraded to java 17 was a really bummer for the few weeks.

**Comment by paul-dingemans** [comment] 2023-05-21 19:47
> Cool. Only thing that might need improvement is the path to the jar file. When downloading a ktlint release the bat and jar file will be in same directory. So maybe you can add a variable for the JAR_PATH and add a comment that this var needs to be changed if bat and jar file are not located in same dir.

```
@echo off
REM By default this batch file and the "ktlint.jar" are located in same directory. Please adjust path below when this batch
REM file and the jar file are located in different directories.
set JAR_PATH=".\ktlint.jar"

REM The --add-opens argument is needed for java 16+ (see https://github.com/pinterest/ktlint/issues/1986)
java --add-opens=java.base/java.lang=ALL-UNNAMED -jar %JAR_PATH% %*
```

Can you please test the script above? 

Also please test with:
* JAR file located in other directory
* Invalid JAR path (if no clear error message is thrown it would be nice if you can add a check for it)

**Comment by zackees** [comment] 2023-05-23 17:48
I'll be back at my windows machine tomorrow and i'll test this.

**Comment by zackees** [comment] 2023-05-25 00:03
It works. However if `JAR_PATH` is already set, your batch file will ignore it.

The following only sets `JAR_PATH` if it is not set:

```
@echo off
REM By default this batch file and the "ktlint.jar" are located in same directory. Please adjust path below when this batch
REM file and the jar file are located in different directories.
if not defined JAR_PATH set JAR_PATH=.\ktlint.jar

REM The --add-opens argument is needed for java 16+ (see https://github.com/pinterest/ktlint/issues/1986)
java --add-opens=java.base/java.lang=ALL-UNNAMED -jar "%JAR_PATH%" %*
```

**Closed** 2023-05-28 09:58 UTC
