### ISSUE TITLE
Add name of the rule to the report

### ISSUE THREAD

**Issue by knyttl** [pinterest/ktlint#1306] opened 2021-12-11 21:11 UTC
## Expected Behavior

Consider a following output:

```
/src/main/kotlin/net/goout/repositories/templating/TimeFormatMethod.kt:217:13: Missing { ... }
/src/main/kotlin/net/goout/repositories/ticketing/PurchaseSearchRepository.kt:665:13: Internal Error (experimental:trailing-comma). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, please re-run with the --debug flag to get the stacktrace and provide the source code that triggered an error) (cannot be auto-corrected)
/src/main/kotlin/net/goout/repositories/ticketing/IsicRepository.kt:46:30: Argument should be on a separate line (unless all arguments can fit a single line)
/src/main/kotlin/net/goout/repositories/ticketing/PurchaseFilters.kt:370:25: Missing { ... }
/src/main/kotlin/net/goout/repositories/entities/VideoRepository.kt:331:13: Internal Error (experimental:trailing-comma). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, please re-run with the --debug flag to get the stacktrace and provide the source code that triggered an error) (cannot be auto-corrected)
/src/main/kotlin/net/goout/repositories/entities/ImageRepository.kt:17:13: Missing { ... }
/src/main/kotlin/net/goout/repositories/entities/InnerTagRepository.kt:16:24: Argument should be on a separate line (unless all arguments can fit a single line)
/src/main/kotlin/net/goout/servicecallers/ElasticServiceCaller.kt:18:53: Argument should be on a separate line (unless all arguments can fit a single line)
/src/main/kotlin/net/goout/servicecallers/LocationsServiceCaller.kt:108:54: Unnecessary trailing comma before ")"
/src/main/kotlin/net/goout/services/PurchaseTransactionsService.kt:573:7: Annotations should occur immediately before the annotated construct
/src/test/kotlin/net/goout/model/ticketing/PurchaseTest.kt:36:9: Unexpected indentation (expected 4, actual 8)
```

Some of the rules I would like to disable, but in fact I am unable to see which rule results in which error. It would be great to see the rule name, eg:

```
(annotations-before-construct) /src/main/kotlin/net/goout/services/PurchaseTransactionsService.kt:573:7: Annotations should occur immediately before the annotated construct
(experimental:indent) /src/test/kotlin/net/goout/model/ticketing/PurchaseTest.kt:36:9: Unexpected indentation (expected 4, actual 8)
```

## Current Behavior
The report doesn't contain the rule names.

## Additional information
* Current version of ktlint: 0.43.2

**Comment by romtsn** [comment] 2021-12-12 15:31
duplicate of #1121

**Closed by romtsn** 2021-12-12 15:31 UTC
