### ISSUE TITLE
Full path is no longer being reported

### ISSUE THREAD

**Issue by vanniktech** [pinterest/ktlint#2016] opened 2023-05-12 16:19 UTC
With version 0.47.1 I always got the full path in the command line (via the console reporter): 

> /Users/niklas/dev/GitHub/vanniktech/app-location-history/src/androidTest/kotlin/com/vanniktech/locationhistory/screenshots/LocationHistoryScreenshotsTest.kt:33:1: Annotation with parameter(s) should be placed on a separate line prior to the annotated construct (annotation)

That allowed me to directly click on it and open the file. With 0.49.0 this behavior is gone and I only see:

> src/androidTest/kotlin/com/vanniktech/locationhistory/screenshots/LocationHistoryScreenshotsTest.kt:33:1: Annotation with parameter(s) should be placed on a separate line prior to the annotated construct (annotation)

Which isn't clickable since I'm in the `/Users/niklas/dev/GitHub/vanniktech/` directory. 

Why was this behavior changed? I'd prefer the old behavior.

**Comment by paul-dingemans** [comment] 2023-05-12 19:14
Duplicate of #1983. Will be fixed in 0.49.1 which is being released today.

**Closed** 2023-05-12 19:14 UTC

**Comment by vanniktech** [comment] 2023-05-12 20:08
Indeed, works with 0.49.1 👍
