### ISSUE TITLE
ktlint format throws exception

### ISSUE THREAD

**Issue by pvegh** [pinterest/ktlint#1227] opened 2021-09-06 11:45 UTC
./ktlint --format "foo/**/*.kt" "!foo/**/generated/**"

Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class org.jetbrains.kotlin.com.intellij.openapi.util.objectTree.ThrowableInterner
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:575)
	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:547)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:298)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:262)
	at com.pinterest.ktlint.Main.main(Main.kt:70)

The same command without format works (shows warnings)

0.42.1 command line, MacOS

**Comment by paul-dingemans** [comment] 2021-09-07 18:50
I have tried to reproduce your problem, but failed at it.  I put content below into a file with name 'Bar.kt' inside directory 'foo' and a copy of it in directory 'foo/generated'.
```
package foo

    val x =1000
```

The command `ktlint --format "foo/*.kt" "!foo/generated/**"` formats the file in directory 'foo' but does not modify 'foo/generated'. Can you replicate this on your machine? If this example works on your machine, the problem is most likely caused by a specific file in your directory.  Please run with option '--debug' and see whether you can identify the file that is causing the problem.

**Comment by pvegh** [comment] 2021-09-08 11:53
I'm getting a very similar but little different stacktrace when setting it up in /tmp.

./ktlint --format "foo/*.kt"

Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:575)
	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:547)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:298)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:262)
	at com.pinterest.ktlint.Main.main(Main.kt:70)
Caused by: java.lang.ExceptionInInitializerError
	at org.jetbrains.kotlin.com.intellij.util.exception.FrequentErrorLogger.report(FrequentErrorLogger.java:46)
	at org.jetbrains.kotlin.com.intellij.util.exception.FrequentErrorLogger.info(FrequentErrorLogger.java:42)

btw I downloaded it as follows, don't have it in my path, but locally in the project. Maybe that's a difference?
curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint

**Comment by paul-dingemans** [comment] 2021-09-11 19:59
I can only reproduce this when java16 (see below) is installed. 
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)
```

Can you confirm that you have java16 installed as well?

**Comment by pvegh** [comment] 2021-09-12 15:10
Confirmed

**Comment by romtsn** [comment] 2021-12-14 10:43
Closing in favour of #1195

**Closed by romtsn** 2021-12-14 10:43 UTC
