### ISSUE TITLE
ktlint doesn't work after update Kotlin to 1.3.30

### ISSUE THREAD

**Issue by kirich1409** [pinterest/ktlint#375] opened 2019-04-12 10:12 UTC
After upgrade to Kotlin 1.3.30 ktlint doesn't work and crash with exception

```
Exception in thread "main" java.lang.NoSuchFieldError: PROPERTY_DELEGATE
        at com.github.shyiko.ktlint.core.ast.ElementType.<clinit>(ElementType.kt:33)
        at com.github.shyiko.ktlint.ruleset.standard.ChainWrappingRule.<init>(ChainWrappingRule.kt:36)
        at com.github.shyiko.ktlint.ruleset.standard.StandardRuleSetProvider.get(StandardRuleSetProvider.kt:12)
        at com.github.shyiko.ktlint.Main.main(Main.kt:310)
```

**Comment by nzakharchenko** [comment] 2019-04-12 12:45
We have exactly the same issue :(

**Comment by shashachu** [comment] 2019-04-16 19:03
@kirich1409 or @nzakharchenko can you submit a small sample project to reproduce the issue?

**Comment by rom4ek** [comment] 2019-04-16 21:00
@shashachu I believe #376 fixes it. But is there a following patch release coming with the new executable?

**Comment by shashachu** [comment] 2019-04-16 21:07
@rom4ek I wasn't clear if they were the same issue as #376 didn't change anything about `PROPERTY_DELEGATE`, which is why I wanted a test case.

**Comment by shashachu** [comment] 2019-04-16 21:10
But to answer your question, assuming this fixes the issue we can make a minor release.

**Comment by rom4ek** [comment] 2019-04-16 21:41
@shashachu Thanks for the answer! Looking at [this](https://github.com/JetBrains/kotlin/commit/046a35bcda4368d885ae569c74f97d1e48f2b5fc), I assume it just got resolved by re-compiling with the newer kotlin version, since the public type has changed. Also afaik when you do `mvn clean verify`, it also runs ktlint over itself, so the build on the PR would've failed, if this was an issue.

**Comment by shashachu** [comment] 2019-04-16 23:16
@rom4ek there are some housekeeping items that we need to do on the Pinterest side before we can make a next official release - I'll throw up a snapshot for people that want to get locally unblocked.

**Comment by shashachu** [comment] 2019-04-16 23:28
Snapshot here https://github.com/pinterest/ktlint/releases/tag/0.31.0-SNAPSHOT

**Comment by shashachu** [comment] 2019-04-16 23:28
Should be fixed with https://github.com/pinterest/ktlint/pull/376

**Closed by shashachu** 2019-04-16 23:28 UTC

**Comment by jeremymailen** [comment] 2019-04-17 05:29
Thank you @shashachu!

Is the maven artifact published anywhere? I'd try to jitpack it myself, but the build isn't compatible
https://jitpack.io/com/github/shyiko/ktlint/0.31.0-SNAPSHOT/build.log

**Comment by nzakharchenko** [comment] 2019-04-17 07:22
@shashachu @jeremymailen Could it be related to the point that the project owner was changed? On Jitpack I've found `0.31.0-SNAPSHOT` version under this URL - `com.github.pinterest:ktlint:0.31.0-SNAPSHOT` 
https://jitpack.io/#pinterest/ktlint/0.31.0-SNAPSHOT

**Comment by jeremymailen** [comment] 2019-04-17 15:21
Oh, of course @nzakharchenko!

Although it still has the same build problem so can't be jitpacked:
https://jitpack.io/com/github/pinterest/ktlint/0.31.0-SNAPSHOT/build.log

**Comment by rom4ek** [comment] 2019-04-17 15:32
I'm not sure that this is the cause of the issue, but I feel like [this](https://github.com/pinterest/ktlint/blob/0.31.0-SNAPSHOT/.travis.yml) should be also switched from `shyiko` to `pintereset` :)

**Comment by nzakharchenko** [comment] 2019-04-17 15:32
@rom4ek yeah, looks like that.

**Comment by shashachu** [comment] 2019-04-17 16:26
Yes, we're kind of figuring out everything as we go along; thanks for bearing with us. Stanley left a great handoff doc but there's all these little details here and there that need to be updated. I think maybe I didn't set the version properly for the snapshot. I'll take a look in a bit.

**Comment by shashachu** [comment] 2019-04-17 17:10
Actually looks like it's been failing with that error for some time now: https://jitpack.io/com/github/shyiko/ktlint/0.29.0/build.log

**Comment by jeremymailen** [comment] 2019-04-18 05:45
It turns out jitpack just get confused by the presence of gradle build files.
I've fixed it here: https://github.com/pinterest/ktlint/pull/384

**Comment by shashachu** [comment] 2019-04-19 16:44
fyi @jeremymailen and others: with the 0.32.0 release we are going to be changing the groupId from `com.github.shyiko` -> `com.github.pinterest`. I know this will be a bit disruptive for people but we figured it's better to just rip off the bandaid now. Targeting today for the release.

**Comment by pratik-gaur** [comment] 2021-01-20 13:50
For me upgrading ktlint plugin to latest version which is 0.40.0 at the moment, helped.

**Comment by jonathanzea** [comment] 2021-06-14 10:55
Thank you @pratik-gaur ,
That helped me. 
I encounter this issue when upgrading Micronaut from 2.0.x to 2.5.x 
I had "com.pinterest:ktlint:0.37.2" and I guess It was not compatible anymore with Micronaut 2.5.x
