### ISSUE TITLE
[ktlint 0.37.2] Indentation rules formatting not consistent with Idea / Android Studio

### ISSUE THREAD

**Issue by strangesource** [pinterest/ktlint#788] opened 2020-06-17 09:15 UTC
## Expected Behavior
For the following statement, I expect Idea/Android Studio to have the same formatting behaviour as ktlint:

```
myStatement(parameter1, parameter2, parameter3)

myOtherStatement(parameter1, lambda = {
    otherStatement
})
```

## Observed Behavior
While Idea claims everything is fine and does no reformatting, ktlint reformats as follows:
```
myStatement(parameter1, parameter2, parameter3)

myOtherStatement(
    parameter1,
    lambda = {
        otherStatement
    }
)
```
## Steps to Reproduce

- Insert above snippet in Android Studio
- reformat with IDE -> no change
- execute `ktlintformat` gradle task
- observe described behaviour

## Your Environment

* Version of ktlint used: 0.37.2
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
plugin: "org.jlleitschuh.gradle.ktlint" version "9.2.1"
* Version of Gradle used (if applicable):
* Operating System and version: macOS catalina 10.15.3

**Comment by romtsn** [comment] 2020-06-17 11:51
Duplicate of #764

**Closed by romtsn** 2020-06-17 11:51 UTC

**Comment by strangesource** [comment] 2020-06-17 12:24
In my opinion this is different to  #764 as the problem is not the reformatting itself. I am fine with the new format, I just want the IDE to behave the same as the linter.

**Comment by romtsn** [comment] 2020-06-17 12:49
Which kind of implies that you are not fine with the new format :) What we will most likely do is allow the format from the expected behaviour, and also split the indentation rule into small independent ones so you can disable/enable them easier.

I am also not sure if we can set this setting up for the idea integration, need to check.
