### ISSUE TITLE
Make KTlint compatible with the new K2 mode of IntelliJ Kotlin plugin

### ISSUE THREAD

**Issue by vincentditlevinz** [pinterest/ktlint#2859] opened 2024-11-05 16:56 UTC
When enabling the [K2 mode in IntelliJ](https://blog.jetbrains.com/idea/2024/08/meet-the-renovated-kotlin-support-k2-mode/) we get the following message: 
`Plugin 'Ktlint' wasn't loaded because it's incompatible with the Kotlin plugin in "K2" mode`

We've encountered the issue [KTIJ-10861](https://youtrack.jetbrains.com/issue/KTIJ-10861/K1-Broken-resolve-when-a-library-depends-on-the-sources-of-the-project) since the recent release of IntelliJ 2024.2.4. It occurs only when not enabling K2 mode in our project. 
It would be nice if we didn't have to choose between wrong compilation errors in the editor and a so great linter !

Note also that Jetbrains teams expect to enable K2 mode by default very soon:
> We aim to enable K2 mode by default starting with IntelliJ IDEA 2024.3 by the end of the year

**Comment by paul-dingemans** [comment] 2024-11-05 17:47
This issue should have been raised in the `ktlint-intellij-plugin` repository. It is an duplicate of https://github.com/nbadal/ktlint-intellij-plugin/issues/589.

**Closed by paul-dingemans** 2024-11-05 17:47 UTC
