### ISSUE TITLE
Ktlint deleting semicolon and adding trailing comma after companion object in Enum class

### ISSUE THREAD

**Issue by Ab0o0o0oD** [pinterest/ktlint#1758] opened 2023-01-03 15:26 UTC
## Expected Behavior
I have an enum class with statics function in the companion object: 
```
enum class Foo(val type: String){
      A("a"),
      B("b");

companion object {
      fun from(value: String): Foo {
                  return try {
                      valueOf(value)
                  } catch (e: IllegalArgumentException) {
                      // find by type
              }
          }
}
```

## Observed Behavior
`ktlint --format` deleting the the semicolon `;` and adding a trailing comma `,` after the companion object and raising error:
## Not a valid Kotlin file (12:27 expecting ';' after the last enum entry or '}' to close enum class body) (cannot be auto-corrected) ()

```
enum class Foo(val type: String){
      A("a"),
      B("b")

companion object {
      fun from(value: String): Foo {
                  return try {
                      valueOf(value)
                  } catch (e: IllegalArgumentException) {
                      // find by type
              }
          },
}
```

## Steps to Reproduce
- Perform `ktlint --format`

## Your Environment
* Version of ktlint used: 0.48.0
* Relevant parts of the `.editorconfig` settings: not applicable
* Operating System and version: Ventura 13.1

**Comment by paul-dingemans** [comment] 2023-01-03 17:02
Duplicate of #1733. Will be fixed in `0.48.1`.

**Closed by paul-dingemans** 2023-01-03 17:02 UTC
