### ISSUE TITLE
Merge (instead of overriding) IDEA's code style config

### ISSUE THREAD

**Issue by a141199** [pinterest/ktlint#211] opened 2018-05-11 15:14 UTC
Is there a way to get this feature back? it used to move things like ID to the top and all other kinds of niceties.

**Comment by shyiko** [comment] 2018-05-16 20:47
Hi. 
I'm not sure what you mean but if you are seeing a different behavior in the way Intellij handles XML after you applied `ktlint --apply-to-idea-project` - you must have had a custom code style. You can switch to a previous scheme / change the settings by going to  <kbd>File</kbd> -> <kbd>Settings...</kbd> -> <kbd>Editor</kbd> -> <kbd>Code Style</kbd> -> <kbd>XML</kbd>.

**Comment by Yurii-Laguta** [comment] 2018-05-23 06:46
@shyiko  the problem is that  ```ktlint --apply-to-idea-project``` removes some very valuable settings from ".idea/codeStyles/Project.xml" is there a way to merge them? or add some without removing everything else? or add those configurations to ```ktlint --apply-to-idea-project --android```

**Comment by shyiko** [comment] 2018-05-23 17:21
Thank you, @Yurii-Laguta. I'll take a look.

**Comment by arunvelsriram** [comment] 2019-10-01 09:33
I was looking into the code for fixing this issue. I would like to clarify my understanding of the expected behavior.

**Actual behavior:**

`.idea/codeStyles/Project.xml` is replaced by `ktlint/src/main/resources/project-config/.idea/codeStyles/Project.xml`

**Expected behavior:**

If `.idea/codeStyles/Project.xml` exists then merge it with `ktlint/src/main/resources/project-config/.idea/codeStyles/Project.xml`. When merging, the contents of `ktlint/src/main/resources/project-config/.idea/codeStyles/Project.xml` will be given higher preference.

**Comment by Tapchicoma** [comment] 2019-10-01 11:12
>  When merging, the contents of ktlint/src/main/resources/project-config/.idea/codeStyles/Project.xml will be given higher preference.

I would say this should depend on `--force` flag value.

**Comment by romtsn** [comment] 2020-12-02 12:11
Closing this as we are going to deprecate the current IDEA-integration in favor of integration via `.editorconfig` (#701)

**Closed by romtsn** 2020-12-02 12:11 UTC
Labels: pull-request-welcome
