### ISSUE TITLE
Support -F with --stdin

### ISSUE THREAD

**Issue by alex-shinn** [pinterest/ktlint#1558] opened 2022-07-27 00:16 UTC
## Expected Behavior
It's reasonable to want to use ktlint as a filter, reading Kotlin code on stdin and writing the correctly formatted version to stdout.  Many other auto-formatters work this way, and it's important to be able to call out to ktlint from editors like Emacs and vim.

The separately reported issue to allow a --path=... with --stdin would complement this well.

## Current Behavior
ktlint -F --stdin produces no output.

## Additional information
* Current version of ktlint: 0.46.1

**Comment by paul-dingemans** [comment] 2022-07-27 19:23
Duplicate of https://github.com/pinterest/ktlint/issues/1153. Specifically, see https://github.com/pinterest/ktlint/issues/1153#issuecomment-1176528787

**Closed by paul-dingemans** 2022-07-27 19:23 UTC

**Comment by alex-shinn** [comment] 2022-07-27 22:53
Thanks!  Sorry for the duplicate.
