### ISSUE TITLE
Unused imports are not removed with .* in the end

### ISSUE THREAD

**Issue by YauheniPo** [pinterest/ktlint#1256] opened 2021-10-21 16:50 UTC
.editorconfig:
```
# top-most EditorConfig file
root = true

[**.{kt,kts}]

indent_size=4
insert_final_newline=true
max_line_length=off

# Comma-separated list of rules to disable
disabled_rules=no-wildcard-imports,experimental:argument-list-wrapping,filename,parameter-list-wrapping,spacing-between-declarations-with-annotations

ij_kotlin_imports_layout=*,java.**,javax.**,kotlin.**,^ # default IntelliJ IDEA style, same as alphabetical, but with "java", "javax", "kotlin" and alias imports in the end of the imports list
```

```
import io.ktor.client.*
import io.ktor.client.statement.*
import java.util.*
```
import java.util.* - not using

## Your Environment

* Version of ktlint used: "10.2.0"
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
* Version of Gradle used (if applicable): 6.9.1
* Operating System and version: MacOS
* Link to your project (if it's a public repository):

**Comment by romtsn** [comment] 2021-10-21 17:56
Sorry I don't get the issue - if the `java.util.*` is unused, why should it not be removed?

**Comment by YauheniPo** [comment] 2021-11-02 13:28
Issue reproduced for the current moment with the next setting
`
buildscript {
    dependencies {
        classpath("com.google.protobuf:protobuf-gradle-plugin:${Versions.protobufPlugin}")
        classpath("org.jlleitschuh.gradle:ktlint-gradle:${Versions.ktlintPlugin}")
    }
    repositories {
        maven {
            url = uri("https://plugins.gradle.org/m2/")
        }
    }
}

apply(plugin = "org.jlleitschuh.gradle.ktlint")

plugins {
    kotlin("jvm") version Versions.kotlin
    id("java")
}

tasks.build {
    dependsOn("ktlintFormat")
}

java.sourceCompatibility = JavaVersion.VERSION_1_8

allprojects {
    // Run ktlint check './gradlew ktlintCheck' for returning list of issues
    // Run ktlint format './gradlew ktlintFormat' for fixing issues
    // Add '--continue' option if you don't want to stop task execution in case of some of the subprojects tasks failed
    apply(plugin = "org.jlleitschuh.gradle.ktlint")

    configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        version.set(Versions.ktlintExtension)
        debug.set(true)
        verbose.set(true)
        android.set(false)
        outputToConsole.set(true)
        outputColorName.set("RED")
        ignoreFailures.set(false)
        enableExperimentalRules.set(true)
        reporters {
            reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.HTML)
            reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.CHECKSTYLE)
        }
    }

    task("printVersion") {
        doLast {
            println(version)
        }
    }

    configurations.all {
        exclude(module = "slf4j-log4j12")
    }
}
`
    const val ktlintPlugin = "10.2.0"
    const val ktlintExtension = "0.42.1"
    
@romtsn @JLLeitschuh please help me with the issue

**Comment by YauheniPo** [comment] 2021-11-02 13:33
sorry "0.42.1" is a old version without fix

Who can build new version?

**Comment by paul-dingemans** [comment] 2021-11-02 18:00
You seem to be lucky. Today a new version, 0.43.0 was released in which this fix should be included.

**Comment by abouda** [comment] 2021-11-05 12:42
In 0.43.0 it seems to be removing wild card imports even though they are needed. And I have no-wildcard-import disabled.

        import com.example.ktlinttest.Test.*
        import com.example.ktlinttest.model.*

        val testObj = TestObj
        val testData = TestData(0)

        val testClass1: TestClass1
        val testClass2: TestClass2
Both imports are flagged as "Unnecessary import" and removed.

**Comment by matiascalvo** [comment] 2021-11-05 14:00
I'm having same issue as @abouda

**Comment by YauheniPo** [comment] 2021-11-06 18:56
You can create new issue with your problem of the klint
@abouda @matiascalvo

my issue was resolved in 0.43.0 version

**Comment by YauheniPo** [comment] 2021-11-06 18:57
https://github.com/pinterest/ktlint/issues/1277 from @illuzor

**Comment by YauheniPo** [comment] 2021-11-09 15:51
I see the issue and for the next case

import io.ktor.client.*
_import io.ktor.client.call.*_ - unused import
import io.ktor.client.statement.*

config
```
allprojects {
    // Run ktlint check './gradlew ktlintCheck' for returning list of issues
    // Run ktlint format './gradlew ktlintFormat' for fixing issues
    // Add '--continue' option if you don't want to stop task execution in case of some of the subprojects tasks failed
    apply(plugin = "org.jlleitschuh.gradle.ktlint")

    configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
        version.set(Versions.ktlintExtension)
        debug.set(true)
        verbose.set(true)
        android.set(false)
        outputToConsole.set(true)
        outputColorName.set("RED")
        ignoreFailures.set(false)
        enableExperimentalRules.set(true)
        reporters {
            reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.HTML)
            reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.CHECKSTYLE)
        }
    }
```
@paul-dingemans please help )

**Comment by YauheniPo** [comment] 2021-11-09 15:51
const val ktlintExtension = "0.43.0"

**Comment by YauheniPo** [comment] 2021-11-09 15:52
const val ktlintExtension = "0.43.0"

**Comment by paul-dingemans** [comment] 2021-11-09 18:07
Please be more clear. I do not understand why the issue is reopened. Neither do I understand a stand alone comment like this:

> const val ktlintExtension = "0.43.0"

**Comment by YauheniPo** [comment] 2021-11-09 21:03
Sorry
I am using new fixed version 0.43.0, but I see invalid behavior for case
```
import io.ktor.client.*
import io.ktor.client.call.*     - unused import
import io.ktor.client.statement.*
```
unused import are not removed

above i provided my setting in gradle

**Comment by YauheniPo** [comment] 2021-11-12 15:38
please tell me which setting of klint will prohibit the use * of such imports?

**Comment by paul-dingemans** [comment] 2021-11-12 20:17
I assume that the code sample is not complete as it only contains import statements. I can not analyse why the second import is not removed without the full sample.

Not removing an unused import statement might be unwanted but is not a blocking problem. I suggest you accept that behavior till it is fixed in a future release.

**Comment by paul-dingemans** [comment] 2022-03-12 15:38
The solution for this issue has been reverted. It can lead to removal of wildcard imports that are actually needed to compile the code (see #1277). The downside that some imports which are not used, is considered less harmfull than removal of imports which are required. As we see no solution for how to implement this with reasonable effort, the issue will be closed without resolving it.

**Closed by paul-dingemans** 2022-03-12 15:38 UTC
Labels: bug
