### ISSUE TITLE
ktlint CLI no longer can properly configure Intellij

### ISSUE THREAD

**Issue by bhoogter** [pinterest/ktlint#544] opened 2019-07-25 13:20 UTC
Using ktlint CLI tool (0.34.2) installed on MacOS (10.14.6) via `brew install ktlint`:

Previously, according to the readme, you could run:

> `ktlint --apply-to-idea-project`

and it would cause IntelliJ to "... produce 100% ktlint-compatible code." (quoted from ktlint project readme).  This would happen (on a Mac) when pressing Ctrl+Option+O to reorganize imports, and was working fine up til now.

However, since upgrading from 0.33 to  0.34.2, the optimize imports (^+/+O) cannot fix this issue:

> ` Imports must be ordered in lexicographic order without any empty lines in-between`

Without this, upgrading to 0.34.2 would be more painful than desired...

NOTE:  The CLI command `ktlint -F` still works, of course, but it isn't directly tied into this IDE.

**Comment by shashachu** [comment] 2019-07-25 16:34
Thanks for the report! Closing as a dupe of https://github.com/pinterest/ktlint/issues/527; feel free to re-open if you disagree.

**Closed by shashachu** 2019-07-25 16:34 UTC
