### ISSUE TITLE
`filename` rule should be disabled for files containing a single main function

### ISSUE THREAD

**Issue by Kantis** [pinterest/ktlint#1572] opened 2022-08-04 08:54 UTC
Currently a file containing a single `fun main()` causes a lint violation if the file isn't named `Main.kt`

I think in this case it always makes more sense to name the file according to what the main-function does. Having a package where multiple main entrypoints exist will be impossible to resolve.

**Comment by paul-dingemans** [comment] 2022-08-07 09:02
This issue is a duplicate of the final solution of #1521, see commit: https://github.com/pinterest/ktlint/commit/7abe7da6526a85286b3548bb34f0d59140c83552. It will be released in version 0.47.0.

**Closed by paul-dingemans** 2022-08-07 09:02 UTC
