### ISSUE TITLE
ktlint command: `./ktlint "**/src/**/*.kt" -F` removes symbol `;` from the end of ENUM values

### ISSUE THREAD

**Issue by Kolyall** [pinterest/ktlint#1763] opened 2023-01-04 07:15 UTC
## Expected Behavior
enum class may contain `;` at end of list values

## Observed Behavior
ktlint command: `./ktlint "**/src/**/*.kt" -F`
removes symbol `;` from the end of list values

## Steps to Reproduce
Create enum MyEnums.kt:
```
enum class MyEnums  {
    FIRST,
    SECOND;
    fun isFirst(){
        this == MyEnums.FIRST
    }
}
```
run command:
`./ktlint "**/src/**/*.kt" -F`
in result:
```
enum class MyEnums  {
    FIRST,
    SECOND // symbol `;` was removed , compile error occurs 

    fun isFirst(){
        this == MyEnums.FIRST
    }
}
```

## Your Environment

* Version of ktlint used: 0.48.0
* Version of Gradle used (if applicable): 
```
classpath 'com.android.tools.build:gradle:7.3.1'
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
```
* Operating System and version: Ubuntu 20.04.5 LTS

**Comment by paul-dingemans** [comment] 2023-01-04 16:46
Duplicate of #1733. Is fixed in `0.48.1`.

**Closed by paul-dingemans** 2023-01-04 16:46 UTC
