### ISSUE TITLE
How to exclude generated sources from ktlint --relative?

### ISSUE THREAD

**Issue by Kolyall** [pinterest/ktlint#1834] opened 2023-02-24 07:04 UTC
```
./ktlint --version
0.48.2
```

After run the command from pre-commit:
```
git diff --name-only -z --cached --relative -- '*.kt' '*.kts' | ./ktlint --relative --patterns-from-stdin=''
```
Output is :
```
...
app/build/generated/source/kapt/debug/....kt:46:1: Unexpected indentation (4) (should be 8) (indent)

Summary error count (descending) by rule:
  indent: 464
  parameter-list-wrapping: 194
  wrapping: 194
  curly-spacing: 27
  no-consecutive-blank-lines: 1

```
ktlint also include files from folder: app/build/generated/source/kapt/

**Comment by mfederczuk** [comment] 2023-02-24 13:46
Duplicate of #1793.
This problem is known and has already been fixed, though the fix is not yet released.
In the meanwhile, you can refer to the linked issue for a workaround.

**Comment by paul-dingemans** [comment] 2023-02-24 20:24
@Kolyall You can also use the ktlint snapshot (https://pinterest.github.io/ktlint/install/snapshot-build/) to verify that your problem is solved.

**Closed by paul-dingemans** 2023-02-24 20:24 UTC

**Comment by androideveloper** [comment] 2023-03-09 11:06
Having similar issue with generated code from Kotlin build scripts (under `buildSrc` folder). Can confirm 0.49-snapshot fixes that. But I run ktlint without githooks, any workaround to exclude paths (`buildSrc` folder in this case)?

**Comment by androideveloper** [comment] 2023-03-09 13:57
Thanks! found the docs https://pinterest.github.io/ktlint/install/cli/#globs
Only excluding didn't work, we also need to include smth.
So this worked for me:
```
    "**/*.{kt,kts}",
    "!**/build/**",
```
So this will make sure ktlint is running on both kt and kts files (event in `buildSrc`), but not in the generated `build` folder

**Comment by paul-dingemans** [comment] 2023-03-09 20:32
> Only excluding didn't work, we also need to include smth.

Yes that is correct. The default (include) patters will only be applied whenever no patterns are specified. But that does not make sense when only an exclude pattern is given.
